//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Player.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("عربى")]
        public string btnArabic {
            get {
                return ((string)(this["btnArabic"]));
            }
            set {
                this["btnArabic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string btnEnglish {
            get {
                return ((string)(this["btnEnglish"]));
            }
            set {
                this["btnEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 1")]
        public string btnEMovie1 {
            get {
                return ((string)(this["btnEMovie1"]));
            }
            set {
                this["btnEMovie1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 2")]
        public string btnEMovie2 {
            get {
                return ((string)(this["btnEMovie2"]));
            }
            set {
                this["btnEMovie2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 3")]
        public string btnEMovie3 {
            get {
                return ((string)(this["btnEMovie3"]));
            }
            set {
                this["btnEMovie3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 4")]
        public string btnEMovie4 {
            get {
                return ((string)(this["btnEMovie4"]));
            }
            set {
                this["btnEMovie4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 5")]
        public string btnEMovie5 {
            get {
                return ((string)(this["btnEMovie5"]));
            }
            set {
                this["btnEMovie5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 6")]
        public string btnEMovie6 {
            get {
                return ((string)(this["btnEMovie6"]));
            }
            set {
                this["btnEMovie6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 7")]
        public string btnEMovie7 {
            get {
                return ((string)(this["btnEMovie7"]));
            }
            set {
                this["btnEMovie7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 8")]
        public string btnEMovie8 {
            get {
                return ((string)(this["btnEMovie8"]));
            }
            set {
                this["btnEMovie8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 9")]
        public string btnEMovie9 {
            get {
                return ((string)(this["btnEMovie9"]));
            }
            set {
                this["btnEMovie9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 10")]
        public string btnEMovie10 {
            get {
                return ((string)(this["btnEMovie10"]));
            }
            set {
                this["btnEMovie10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 11")]
        public string btnEMovie11 {
            get {
                return ((string)(this["btnEMovie11"]));
            }
            set {
                this["btnEMovie11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video 12")]
        public string btnEMovie12 {
            get {
                return ((string)(this["btnEMovie12"]));
            }
            set {
                this["btnEMovie12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 1")]
        public string btnAMovie1 {
            get {
                return ((string)(this["btnAMovie1"]));
            }
            set {
                this["btnAMovie1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 2")]
        public string btnAMovie2 {
            get {
                return ((string)(this["btnAMovie2"]));
            }
            set {
                this["btnAMovie2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 3")]
        public string btnAMovie3 {
            get {
                return ((string)(this["btnAMovie3"]));
            }
            set {
                this["btnAMovie3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 4")]
        public string btnAMovie4 {
            get {
                return ((string)(this["btnAMovie4"]));
            }
            set {
                this["btnAMovie4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 5")]
        public string btnAMovie5 {
            get {
                return ((string)(this["btnAMovie5"]));
            }
            set {
                this["btnAMovie5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 6")]
        public string btnAMovie6 {
            get {
                return ((string)(this["btnAMovie6"]));
            }
            set {
                this["btnAMovie6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 7")]
        public string btnAMovie7 {
            get {
                return ((string)(this["btnAMovie7"]));
            }
            set {
                this["btnAMovie7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 8")]
        public string btnAMovie8 {
            get {
                return ((string)(this["btnAMovie8"]));
            }
            set {
                this["btnAMovie8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 9")]
        public string btnAMovie9 {
            get {
                return ((string)(this["btnAMovie9"]));
            }
            set {
                this["btnAMovie9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 10")]
        public string btnAMovie10 {
            get {
                return ((string)(this["btnAMovie10"]));
            }
            set {
                this["btnAMovie10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 11")]
        public string btnAMovie11 {
            get {
                return ((string)(this["btnAMovie11"]));
            }
            set {
                this["btnAMovie11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("الفيلم 12")]
        public string btnAMovie12 {
            get {
                return ((string)(this["btnAMovie12"]));
            }
            set {
                this["btnAMovie12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string btnEFont1 {
            get {
                return ((string)(this["btnEFont1"]));
            }
            set {
                this["btnEFont1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string btnAFont1 {
            get {
                return ((string)(this["btnAFont1"]));
            }
            set {
                this["btnAFont1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("white")]
        public string btnEColor1 {
            get {
                return ((string)(this["btnEColor1"]));
            }
            set {
                this["btnEColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("white")]
        public string btnAColor1 {
            get {
                return ((string)(this["btnAColor1"]));
            }
            set {
                this["btnAColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string pageInfo {
            get {
                return ((string)(this["pageInfo"]));
            }
            set {
                this["pageInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie1E {
            get {
                return ((string)(this["Movie1E"]));
            }
            set {
                this["Movie1E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie2E {
            get {
                return ((string)(this["Movie2E"]));
            }
            set {
                this["Movie2E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie3E {
            get {
                return ((string)(this["Movie3E"]));
            }
            set {
                this["Movie3E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie4E {
            get {
                return ((string)(this["Movie4E"]));
            }
            set {
                this["Movie4E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie5E {
            get {
                return ((string)(this["Movie5E"]));
            }
            set {
                this["Movie5E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie6E {
            get {
                return ((string)(this["Movie6E"]));
            }
            set {
                this["Movie6E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie7E {
            get {
                return ((string)(this["Movie7E"]));
            }
            set {
                this["Movie7E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie8E {
            get {
                return ((string)(this["Movie8E"]));
            }
            set {
                this["Movie8E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie9E {
            get {
                return ((string)(this["Movie9E"]));
            }
            set {
                this["Movie9E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie10E {
            get {
                return ((string)(this["Movie10E"]));
            }
            set {
                this["Movie10E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie11E {
            get {
                return ((string)(this["Movie11E"]));
            }
            set {
                this["Movie11E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie12E {
            get {
                return ((string)(this["Movie12E"]));
            }
            set {
                this["Movie12E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie1A {
            get {
                return ((string)(this["Movie1A"]));
            }
            set {
                this["Movie1A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie2A {
            get {
                return ((string)(this["Movie2A"]));
            }
            set {
                this["Movie2A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie3A {
            get {
                return ((string)(this["Movie3A"]));
            }
            set {
                this["Movie3A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie4A {
            get {
                return ((string)(this["Movie4A"]));
            }
            set {
                this["Movie4A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie5A {
            get {
                return ((string)(this["Movie5A"]));
            }
            set {
                this["Movie5A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie6A {
            get {
                return ((string)(this["Movie6A"]));
            }
            set {
                this["Movie6A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie7A {
            get {
                return ((string)(this["Movie7A"]));
            }
            set {
                this["Movie7A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie8A {
            get {
                return ((string)(this["Movie8A"]));
            }
            set {
                this["Movie8A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie9A {
            get {
                return ((string)(this["Movie9A"]));
            }
            set {
                this["Movie9A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie10A {
            get {
                return ((string)(this["Movie10A"]));
            }
            set {
                this["Movie10A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie11A {
            get {
                return ((string)(this["Movie11A"]));
            }
            set {
                this["Movie11A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string Movie12A {
            get {
                return ((string)(this["Movie12A"]));
            }
            set {
                this["Movie12A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test.mp4")]
        public string url {
            get {
                return ((string)(this["url"]));
            }
            set {
                this["url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA1 {
            get {
                return ((bool)(this["vA1"]));
            }
            set {
                this["vA1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA2 {
            get {
                return ((bool)(this["vA2"]));
            }
            set {
                this["vA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA3 {
            get {
                return ((bool)(this["vA3"]));
            }
            set {
                this["vA3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA4 {
            get {
                return ((bool)(this["vA4"]));
            }
            set {
                this["vA4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA5 {
            get {
                return ((bool)(this["vA5"]));
            }
            set {
                this["vA5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA6 {
            get {
                return ((bool)(this["vA6"]));
            }
            set {
                this["vA6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA7 {
            get {
                return ((bool)(this["vA7"]));
            }
            set {
                this["vA7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA8 {
            get {
                return ((bool)(this["vA8"]));
            }
            set {
                this["vA8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA9 {
            get {
                return ((bool)(this["vA9"]));
            }
            set {
                this["vA9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA10 {
            get {
                return ((bool)(this["vA10"]));
            }
            set {
                this["vA10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA11 {
            get {
                return ((bool)(this["vA11"]));
            }
            set {
                this["vA11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vA12 {
            get {
                return ((bool)(this["vA12"]));
            }
            set {
                this["vA12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE1 {
            get {
                return ((bool)(this["vE1"]));
            }
            set {
                this["vE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE2 {
            get {
                return ((bool)(this["vE2"]));
            }
            set {
                this["vE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE3 {
            get {
                return ((bool)(this["vE3"]));
            }
            set {
                this["vE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE4 {
            get {
                return ((bool)(this["vE4"]));
            }
            set {
                this["vE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE5 {
            get {
                return ((bool)(this["vE5"]));
            }
            set {
                this["vE5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE6 {
            get {
                return ((bool)(this["vE6"]));
            }
            set {
                this["vE6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE7 {
            get {
                return ((bool)(this["vE7"]));
            }
            set {
                this["vE7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE8 {
            get {
                return ((bool)(this["vE8"]));
            }
            set {
                this["vE8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE9 {
            get {
                return ((bool)(this["vE9"]));
            }
            set {
                this["vE9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE10 {
            get {
                return ((bool)(this["vE10"]));
            }
            set {
                this["vE10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE11 {
            get {
                return ((bool)(this["vE11"]));
            }
            set {
                this["vE11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool vE12 {
            get {
                return ((bool)(this["vE12"]));
            }
            set {
                this["vE12"] = value;
            }
        }
    }
}
